### ISSUE TITLE
Panels and Image support?

### ISSUE THREAD

**Issue by zacksleo** [optimistdigital/nova-settings#1]
1. It would be great if it can support Field Panels or multi tabs?
2. If I put a Image Field, It got an error  when submitting without image change

```
        \OptimistDigital\NovaSettings\NovaSettings::setSettingsFields([
            Image::make('qrcode','qrcode'),
        ]);
```

```
Undefined property: stdClass::$qrcode",
```

**Comment by Tarpsvo** [comment]
Hey! Thanks for reporting this issue.

I added Panel support in 1.1.0. I've yet to look into the `Image` field issue.

**Comment by Tarpsvo** [comment]
Added Image support with deletion in version 1.2.0.
