### ISSUE TITLE
[request] Reload page on save

### ISSUE THREAD

**Issue by pzmarzly** [optimistdigital/nova-settings#10]
I use Nova Settings for color fields, to let admins control their site appearance (including Nova, via CSS variables and `timothyasp/color`). But since Nova is a SPA, I'd need to somehow execute `location.reload()` after the form is saved, ideally somewhere around here:

https://github.com/optimistdigital/nova-settings/blob/cba4c547c4df1fe0d323a3547ae39abe45d92306/resources/js/views/Settings.vue#L81-L94

I can't think of any useful hooks on JS side other than the reload one, but maybe someone will want PHP hooks one day (for dropping caches after settings are saved, etc.).

**Comment by royduin** [comment]
Why is a reload needed?

**Comment by pzmarzly** [comment]
For my use case, I'm changing nova theme by putting

```html
<style>
:root {
    --primary: {{ nova_get_setting('primary_color') ?? '#A41616' }};
    --secondary: {{ nova_get_setting('secondary_color') ?? '#BA8E87' }};
}
</style>
```

to my `resources/views/layouts/partials/theme.blade.php` file.

But I suspect there are other aspects of Nova that can be customized but require a full page reload (maybe enabling/disabling an item in the sidebar?).

**Comment by Tarpsvo** [comment]
Hey! Added a config file with `reload_page_on_save` option in version 2.4.0. Good luck!
