### ISSUE TITLE
Readme needs updating for authorization hide / show settings

### ISSUE THREAD

**Issue by Bryan-Lund** [optimistdigital/nova-settings#108]
I tried restricting the users that could see the settings by what was in the readme, but it didn't work. I.e. this bit:
```
public function tools(): array
{
    return [
        NovaSettings::make()->canSee(fn () => user()->isAdmin()),
    ];
}
```

I had to put `Auth::` in front of the `user()` like so to get it working. Unless i'm missing something, this should be updated:
```
public function tools(): array
{
    return [
        NovaSettings::make()->canSee(fn () => Auth::user()->isAdmin()),
    ];
}
```

**Comment by kevariable** [comment]
it's general example, doesn't mean you gonna take all of an example

**Comment by Tarpsvo** [comment]
You can create a helper `function user() { return Auth::user(); }`. 😉
