### ISSUE TITLE
->rules('required') does not display the asterisk*

### ISSUE THREAD

**Issue by cgarofalo** [optimistdigital/nova-settings#12]
`->rules('required')` does not display the asterisk*.  In Nova Resources, this rule alone is enough to display the asterisk *.  In Nova Settings I have to use `->rules('required')->required()` to show the asterisk and actually have it validate.

**Comment by Tarpsvo** [comment]
Hi! Thanks for reporting this, fixed in version 2.4.3. Good luck!
