### ISSUE TITLE
Can group the settings?

### ISSUE THREAD

**Issue by lifeblood** [optimistdigital/nova-settings#16]

**Comment by Tarpsvo** [comment]
Currently, you can use Nova Panels to group the settings, but I am thinking of adding tabs to the UI as some of my projects also have a ridiculously long list of settings.

**Comment by doyevaristo** [comment]
can you support this package for adding tabs? 
https://novapackages.com/packages/digital-creative/resource-navigation-tab

**Comment by Tarpsvo** [comment]
Tabs would be great, PR-s are welcome.
