### ISSUE TITLE
Horizontal tabs for groupings

### ISSUE THREAD

**Issue by doyevaristo** [optimistdigital/nova-settings#17]
Is there a plan to integrate this setting to this package? 
https://novapackages.com/packages/digital-creative/resource-navigation-tab

**Comment by Tarpsvo** [comment]
Hi! PR-s are welcomed. :)

**Comment by doyevaristo** [comment]
will definitely do this. :)

**Comment by Tarpsvo** [comment]
Hi!

Version 2.6.0 now adds support for subpages and nova-tabs.

Give it a try! Good luck!
