### ISSUE TITLE
How I get translatable value via helper function?

### ISSUE THREAD

**Issue by sharenjoy** [optimistdigital/nova-settings#20]
I think that this package support spatie/laravel-translatable. How I get translatable value via helper function?

**Comment by Landish** [comment]
Let's assume you are using this package https://github.com/optimistdigital/nova-translatable to translate settings with spatie/laravel-translatable. 

```php
Text::make('Some Setting', 'setting_key')->translatable(),
```

```php
json_decode(nova_get_setting('setting_key'), true)[app()->getLocale()]
```

**Comment by Tarpsvo** [comment]
You can make your own helper for these cases.

```
function nova_get_translatable_setting($key, $lang = 'en') {
  return nova_get_setting($key)[$lang] ?? null;
}
```

**Comment by mialyGit** [comment]
@Tarpsvo where do I make this helper please ?, I'am also using https://github.com/optimistdigital/nova-translatable
