### ISSUE TITLE
Panels do not support limit option

### ISSUE THREAD

**Issue by martijn94** [optimistdigital/nova-settings#22]
The panels feature does not support the `->limit()` feature added in nova 2. 

https://nova.laravel.com/docs/3.0/resources/fields.html#field-panels

Would be nice to have this to make the settings view way more organized.

May look into a PR when my project is finished.

Thanks for creating this.

**Comment by Tarpsvo** [comment]
The `->limit()` function only works on detail view, but this package renders the whole view as if it was a form. Might be tricky to get it working.
