### ISSUE TITLE
Ability to change Model / Cache Values

### ISSUE THREAD

**Issue by mstaack** [optimistdigital/nova-settings#23]
Using this on highly used routes adds a db query of course.

Have you thought about adding a caching layer? Which gets flushed on update?

Or adding a configurable Model Class to the `config.php` would help

Cheers max

**Comment by Tarpsvo** [comment]
2.5.1 was released with the option to override the Settings model. Does that help you out?

**Comment by mstaack** [comment]
thanks for the changes!

works brilliant with https://github.com/renoki-co/laravel-eloquent-query-cache

cheers max
