### ISSUE TITLE
Feature: Multiple Settings Pages

### ISSUE THREAD

**Issue by lstoyanoff** [optimistdigital/nova-settings#27]
Hey, I've recently needed multiple settings pages in a project and tried "extending" this awesome package.

You can check my idea, polish it and eventually make it official -- https://github.com/lstoyanoff/nova-settings/commit/b6b3dcc8dd6cca3109ac8e7da6a66fed2275fba6

_Note: Currently, only the default settings page will be shown in the navigation. Every additional page should be manually added in the nova navigation by overriding._

**Comment by Tarpsvo** [comment]
Hi @lstoyanoff! We implemented pretty much an exact copy of your solution in our package (thanks to @MarikaMustV). It was released in version 2.6.0. Do check it out, good luck!
