### ISSUE TITLE
How to translate sidebar lable?

### ISSUE THREAD

**Issue by PoojaJadav** [optimistdigital/nova-settings#33]
I want to translate this sidebar lable Settings. How can I translate?
![image](https://user-images.githubusercontent.com/56014892/97897358-6003f180-1d5c-11eb-8dd3-aeb16d9de8c5.png)

**Comment by Tarpsvo** [comment]
Check README, localization section.

**Comment by PoojaJadav** [comment]
> Check README, localization section.

I tried. but it's not working :(

**Comment by Tarpsvo** [comment]
Is your `app()->getLocale()` correct?

**Comment by PoojaJadav** [comment]
> Is your `app()->getLocale()` correct?

Yes... Other all labels translated except this. 
My code is like this in .../resources/lang/vendor/nova-settings/de.json files:

` "novaSettings.navigationItemTitle": "Einstellungen",
    "novaSettings.saveButtonText": "Einstellungen speichern",`

Check the below screen short. 
![image](https://user-images.githubusercontent.com/56014892/97972787-10b8d200-1deb-11eb-99ae-e4d1810c5a0b.png)

**Comment by Tarpsvo** [comment]
Hmm.... It's possible the locale is set too late. Is it possible for you to call `app()->setLocale()` any earlier?

**Comment by PoojaJadav** [comment]
> Hmm.... It's possible the locale is set too late. Is it possible for you to call `app()->setLocale()` any earlier?

I have already set the locale on Http/kernel. :)

**Comment by PoojaJadav** [comment]
I got translation on fields, if I move "Registering fields" boot() to tools(). But still, button and label are not translated. 

![image](https://user-images.githubusercontent.com/56014892/97981616-968f4a00-1df8-11eb-8115-60005ce6e4ac.png)

**Comment by PoojaJadav** [comment]
I got translations after update the package version :)
