### ISSUE TITLE
Applying a policy on the Settings model has no effect

### ISSUE THREAD

**Issue by Sitethief** [optimistdigital/nova-settings#39]
I could not get a Policy working on the `Settings` model. I tried the automatic way just by making a `SettingsPolicy`, and also tried registering the policy in the `AuthServiceProvider`. 
I quick fixed it with a temporary solution by wrapping the fields in `NovaServiceProvider` in an if statement dependent on the user permissions, but this still has the drawback of the settings page still being visible, albeit empty. 

Am I missing something, or is this simply not implemented? or is there maybe a way to do this that I haven't found yet?

**Comment by medvinator** [comment]
@Sitethief you can use [authorization for tool](https://nova.laravel.com/docs/3.0/customization/tools.html#authorization)

like this (`app/Providers/NovaServiceProvider.php`)
```php
public function tools(): array
{
    return [
        NovaSettings::make()->canSee( fn() => is_user_can_settings() ),
    ];
}
```

**Comment by Tarpsvo** [comment]
Hi @Sitethief!

I added support for per-field authorization in version 3.1.0. If you want to hide the whole thing from the sidebar, I think @medvinator provided a pretty good solution.

I also added it to the README: https://github.com/optimistdigital/nova-settings#authorization

Thanks and good luck guys!

**Comment by Sitethief** [comment]
Yes, that works!
Thanks!
