### ISSUE TITLE
Nova Field rules do not work

### ISSUE THREAD

**Issue by cgarofalo** [optimistdigital/nova-settings#4]
The `->rules()` method does not work on the fields.

**Comment by royduin** [comment]
Fixed: https://github.com/optimistdigital/nova-settings/pull/7

**Comment by Tarpsvo** [comment]
Released in version 1.4.0. (Also let it be said, the previous version "2.3.0" was a typo and was supposed to be "1.3.0").

**Comment by royduin** [comment]
No problem, thanks @Tarpsvo 👍

**Comment by royduin** [comment]
2.3.0 is still visible at Packagist, maybe resync them @Tarpsvo? https://packagist.org/packages/optimistdigital/nova-settings#2.3.0

**Comment by Tarpsvo** [comment]
Thanks for letting me know! Deleted the version manually.

**Comment by cantThinkOfAnything-1** [comment]
Hello I am not sure if this is fixed. For example if I use ` >min(0) ->rules('min: 0')` on a Number field the select buttons don't allow me to choose a negative number but I manually type it into the field, it will save with for example(-150) and update my .env with the negative number. I am using 1.4.0 version but also tried it with the last version and the outcome was the same.

**Comment by Tarpsvo** [comment]
@cantThinkOfAnything-1 Hi! Sorry for the late response. I tested it and it seems like you have to ensure it's a numeric value you're checking the 'min' of. So, the rule should be:

```
->rules('numeric', 'min:0')
```

**Comment by cantThinkOfAnything-1** [comment]
That works. Thank you for your help @Tarpsvo
