### ISSUE TITLE
Request: Make Fields compatible with Nova Translatable

### ISSUE THREAD

**Issue by cgarofalo** [optimistdigital/nova-settings#5]
The package: https://github.com/spatie/nova-translatable
This is probably possible if you allow the value to be a json string and store values like `{'en':'English', 'fr':'French'}`

**Comment by royduin** [comment]
Support is added in version 2.3.0, example usage can be found in the PR: https://github.com/optimistdigital/nova-settings/pull/6

**Comment by Tarpsvo** [comment]
Hey, just letting you know that I released my own `nova-translatable` package that support `nova-settings` and validation rules flawlessly. Try it out at [optimistdigital/nova-translatable](https://github.com/optimistdigital/nova-translatable).

**Comment by royduin** [comment]
Thanks for the heads up!
