### ISSUE TITLE
Setting page is being displayed

### ISSUE THREAD

**Issue by aliraza371** [optimistdigital/nova-settings#50]
I installed this package, Its sidebar option appeared but unable to click on it. Upon Investigation I see the router-link class is not there. It seems it's trying to add subpages instead of the default page.

**Comment by Tarpsvo** [comment]
Have you defined any settings fields? If not, the link will not be clickable.

**Comment by aliraza371** [comment]
Yes, I have defined the settings field as the documentation in the Boot method.

**Comment by Tarpsvo** [comment]
Please provide the code you used to register the fields.

I'm unable to reproduce the issue you're having.

**Comment by aliraza371** [comment]
I just re-installed the package, And somehow it's working now.  Thanks

Can you tell me how I can define multiple panels on one page?

**Comment by Tarpsvo** [comment]
Cool! Just create the Panel as usual?

```
Panel::make('Something', [
    Text::make('Here'),
]),
```
