### ISSUE TITLE
Issue deleting Images

### ISSUE THREAD

**Issue by smartie19889** [optimistdigital/nova-settings#57]
Version 3.1.2 - Nova Version: 3.23.2

When trying to delete an uploaded image, nothing happens, but the console log returns "/nova-api/nova-settings/settings/field/brand_logo"

**Comment by MartinPetricko** [comment]
This issue will occur only when you use subpages without any fields defined for General settings because of check in middleware.

**Comment by Tarpsvo** [comment]
Hi! Thank you for reporting this issue. :) There was indeed a bug and it's now resolved in version 3.1.3. Good luck!
