### ISSUE TITLE
Localization dose not work

### ISSUE THREAD

**Issue by monem2077** [optimistdigital/nova-settings#69]
![Screenshot from 2021-05-31 11-19-00](https://user-images.githubusercontent.com/79110310/120171217-19974800-c202-11eb-909e-75e0ee3c1b1c.png)

**Comment by medvinator** [comment]
Check #53

**Comment by Tarpsvo** [comment]
Heya! Can you try running `composer update` and checking if `nova-translations-loader` version `3.1.2` fixes it for you? Thank you!
