### ISSUE TITLE
Laravel octane problem

### ISSUE THREAD

**Issue by bsormagec** [optimistdigital/nova-settings#87]
When trying to use with octane, Settings appears 3 times everywhere. I am attaching pictures below. Do you have any idea about the situation @simonhamp ?
Thank you.
<img width="1475" alt="screenshot 6(18)" src="https://user-images.githubusercontent.com/965219/141447322-a02614a4-7fb3-422f-ba25-884bc16114ea.png">
<img width="1484" alt="screenshot 6(14)" src="https://user-images.githubusercontent.com/965219/141447358-267e0084-2115-4f76-b2e6-2fa6352f03a9.png">

**Comment by Tarpsvo** [comment]
Ah crap, it might be that the static data is leaking between instances and it's being filled multiple times. I might have to make the data non-static and tie it to the app as a singleton class.

**Comment by bsormagec** [comment]
> Ah crap, it might be that the static data is leaking between instances and it's being filled multiple times. I might have to make the data non-static and tie it to the app as a singleton class.

I can't find the solution and just wanna mention you here thank you for your answer. When you did these changes. I can decrease my vapor invoice :) Thank you. @Tarpsvo

**Comment by bsormagec** [comment]
Thank you @Tarpsvo i am testing and giving feedback ASAP!

**Comment by bsormagec** [comment]
Hello @Tarpsvo.
It worked! 
Thank you so much! 
We can close the issue now, great work!

**Comment by Tarpsvo** [comment]
Awesome, glad to hear that. :)
