### ISSUE TITLE
Translatable fields don't work in view

### ISSUE THREAD

**Issue by nbartokos** [optimistdigital/nova-settings#89]
Hey,

I noticed that my translated fields are shown correct on the nova-settings page, but the fields on my homepage are shown as json string.

**On my homepage I use:**
`{!! nova_get_setting('contact_email') !!}`

**Output:**
`{"en":"email@gmail.com","de":"email@gmail.at"}`

**On nova-settings:**
![image](https://user-images.githubusercontent.com/16653768/144413579-6e6d4ce1-644a-41f6-a610-fec48be2762f.png)

**I used the "HasTranslations" class in my own Settings-Model:**
![image](https://user-images.githubusercontent.com/16653768/144413760-9975962d-cc25-4c02-90a2-5c8eb95e5cc1.png)

**I changed the _nova_get_setting_ function in the _helpers.php_ File as following:**
![image](https://user-images.githubusercontent.com/16653768/144414035-5ff57433-3fbe-4d7a-848d-a9f0df5c28e1.png)

After this "small" change, everything works perfect now. So did I do something wrong or is this a bug? I works for me now, but I want to know, If I messed something up or found a bug.

**Comment by Tarpsvo** [comment]
Hmm, you should cast the `contact_email` to array using the cast functionality in this package. Then when accessing the value, you should access the corresponding locale key.

So basically, you would have:
```php
NovaSettings::addSettingsFields([
  Text::make('Contact email', 'contact_email'),
], ['contact_email' => 'array'], 'Common');

// ...

$email = nova_get_setting('contact_email')[$locale];
```

That's the easiest way to handle it right now.
