### ISSUE TITLE
[request] Translatable messages

### ISSUE THREAD

**Issue by pzmarzly** [optimistdigital/nova-settings#9]
There are some hardcoded strings, such as:

- `Settings successfully updated`
- `No settings fields have been defined.`
- `Error`

It would be nice to be able to translate them via `.js` files in `resources/lang`. I think there is some way to get `__` as Vue helper, if not, you can easily reimplement it:

```js
let __ = function (original) {
    let translated = window.config.translations[original];
    if (translated !== undefined) return translated;
    return original;
}
```

**Comment by Tarpsvo** [comment]
Added translations support in version 2.3.0. Good luck!
